blank_issues_enabled: false
contact_links:
  - name: 🗨 Discussions
    url: https://github.com/Mubelotix/my-morphe-patches/discussions
    about: Ask questions or discuss ideas for these custom patches.
